### ISSUE TITLE
freshenRemoteObject throwing exception if files exist

### ISSUE THREAD

**Issue by cin** [instaclustr/cassandra-backup#26]
I'm trying to get cassandra-backup to work on IBM Cloud with its Cloud Object Storage (COS). COS is supposed to be compatible with AWS' S3 APIs. However, updating and freshening files is throwing exceptions regarding the MetadataDirective being used. This is currently set to [COPY in the code](https://github.com/instaclustr/cassandra-backup/blob/master/src/main/java/com/instaclustr/cassandra/backup/s3/BaseS3Backuper.java#L67). If I change this to REPLACE, it works. I'm not sure of the impact on performance this may have, but I'm not sure I have a choice. I'm looking for some guidance/feedback on possible workarounds and whether or not you guys would be open to a PR to make this configurable?

```
[pool-2-thread-10] WARN com.instaclustr.cassandra.backup.impl.backup.Backuper - Failed to freshen file 'data/system_auth/resource_role_permissons_index-5f2fbdad91f13946bd25d5da3a5c35ec/14-1923991717/md-14-big-Summary.db'.
com.amazonaws.services.s3.model.AmazonS3Exception: The x-amz-metadata-directive you specified was invalid. (Service: Amazon S3; Status Code: 400; Error Code: InvalidRequest; Request ID: daead122-6916-49bb-95d1-f12a03e47724; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1811)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1395)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1371)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5062)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5008)
        at com.amazonaws.services.s3.AmazonS3Client.copyObject(AmazonS3Client.java:2022)
        at com.amazonaws.services.s3.transfer.internal.CopyCallable.copyInOneChunk(CopyCallable.java:145)
        at com.amazonaws.services.s3.transfer.internal.CopyCallable.call(CopyCallable.java:133)
        at com.amazonaws.services.s3.transfer.internal.CopyMonitor.call(CopyMonitor.java:132)
        at com.amazonaws.services.s3.transfer.internal.CopyMonitor.call(CopyMonitor.java:43)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

```
[pool-2-thread-3] ERROR com.instaclustr.cassandra.backup.impl.backup.Backuper - Failed to upload file 'data/system_auth/role_permissions-3afbe79f219431a7add7f5ab90d8ec9c/14-2255245210/md-14-big-Summary.db
com.amazonaws.services.s3.model.AmazonS3Exception: The x-amz-metadata-directive you specified was invalid. (Service: Amazon S3; Status Code: 400; Error Code: InvalidRequest; Request ID: 09afd8b7-4333-4ea6-8edc-fafacfbd152c; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1811)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1395)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1371)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5062)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5008)
        at com.amazonaws.services.s3.AmazonS3Client.copyObject(AmazonS3Client.java:2022)
        at com.amazonaws.services.s3.transfer.internal.CopyCallable.copyInOneChunk(CopyCallable.java:145)
        at com.amazonaws.services.s3.transfer.internal.CopyCallable.call(CopyCallable.java:133)
        at com.amazonaws.services.s3.transfer.internal.CopyMonitor.call(CopyMonitor.java:132)
        at com.amazonaws.services.s3.transfer.internal.CopyMonitor.call(CopyMonitor.java:43)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by smiklosovic** [comment]
@cin hi, sorry for late reply, yes, this might be very likely just changed to REPLACE I would say.

There is also "Oracle s3" (wow these guys are such copycats :) ) and one business of ours who are uploading stuff there want hit this issue that metadata were not specified and that implementation in Oracle cloud needed that. So we used COPY instead REPLACE but I think it doesnt make any difference in our scenario. 

What protocol you are using? Do you specify "s3://bucket..."? There are some special requirements for Oracle cloud so we introduced "oracle://" too with all its quirks.

**Comment by smiklosovic** [comment]
I love the PR! Looks good, I ll cut alpha5 soonish (today most probably).

**Comment by cin** [comment]
We use the `s3://` protocol. AFAICT it's working seamlessly so far. I still need to test large datasets but so far so good!

**Comment by smiklosovic** [comment]
alpha5 is released, closing.
